version: '3.8'

services:
  app:
    image: akshayimage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/library
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: Root
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
